#import "
//  ios-shared Framework.h"
//  ios-shared Framework
//
//  Created by John Clayton on 3/3/16.
//  Copyright © 2016 SetDirection. All rights reserved.
#import "

#import <UIKit/UIKit.h">

//! Project version number for ios-shared Framework.
FOUNDATION_EXPORT double ios_shared_FrameworkVersionNumber;

//! Project version string for ios-shared Framework.
FOUNDATION_EXPORT const unsigned char ios_shared_FrameworkVersionString[];

#import "PublicHeader.h">


#import "NSArray+SDExtensions.h"
#import "NSData+SDExtensions.h"
#import "NSDate+SDExtensions.h"
#import "NSDictionary+SDExtensions.h"
#import "NSError+SDExtensions.h"
#import "NSLayoutConstraint+SDExtensions.h"
#import "NSMutableAttributedString+SDExtensions.h"
#import "NSNumber+SDExtensions.h"
#import "NSRunLoop+SDExtensions.h"
#import "NSString+SDExtensions.h"
#import "NSUserDefaults+SDExtensions.h"
#import "SDBase64.h"
#import "SDCompletionGroup.h"
#import "SDDataMap.h"
#import "SDDecimalNumberTransformer.h"
#import "SDISO8601DateTransformer.h"
#import "SDModelObject.h"
#import "SDPoser.h"
#import "SDPromise.h"
#import "SDTimer.h"
#import "SDURLRouteHandler.h"
#import "SDURLRouter.h"
#import "SDURLRouterEntry.h"
#import "SDWeakArray.h"
#import "UIDevice+machine.h"
#import "UIResponder+SDExtensions.h"
#import "ios-shared.h"
#import "SDLog.h"
#import "ObjectiveCGenerics.h"
#import "SDAssert.h"
#import "SDMacros.h"
#import "CLLocation+SDExtensions.h"
#import "MKMapView+SDExtensions.h"
#import "SDLocationManager.h"
#import "SDBaseMockCLLocationManager.h"
#import "SDKeychain.h"
#import "SDTouchID.h"
#import "SDABTesting.h"
#import "NSObject+SDExtensions.h"
#import "NSShadow+SDExtensions.h"
#import "SDAlertView.h"
#import "SDApplication.h"
#import "SDAutolayoutStackView.h"
#import "SDButton.h"
#import "SDCheckbox.h"
#import "SDCollapsableContainerView.h"
#import "SDContainerViewController.h"
#import "SDContentAlertView.h"
#import "SDCard.h"
#import "SDCardNumber.h"
#import "SDCardType.h"
#import "SDCCTextField.h"
#import "SDCreditCardField.h"
#import "SDDeckController.h"
#import "SDDragDropGestureRecognizer.h"
#import "SDDragDropManager.h"
#import "SDExpandingTableViewController.h"
#import "SDFormFieldContainer.h"
#import "SDHitButton.h"
#import "SDImageButton.h"
#import "SDLabel.h"
#import "SDMultilineLabel.h"
#import "SDNavigationBarSearchField.h"
#import "SDNumberTextField.h"
#import "SDPaddedLabel.h"
#import "SDPagingView.h"
#import "SDPhotoImageView.h"
#import "SDPickerModalViewController.h"
#import "SDPickerView.h"
#import "SDPullNavigation.h"
#import "SDPullNavigationAutomation.h"
#import "SDPullNavigationBar.h"
#import "SDPullNavigationBarAdornmentView.h"
#import "SDPullNavigationBarBackground.h"
#import "SDPullNavigationBarControlsView.h"
#import "SDPullNavigationBarTabButton.h"
#import "SDPullNavigationManager.h"
#import "SDAdjustableItem.h"
#import "SDPaintCodeButton.h"
#import "SDQuantityEditView.h"
#import "SDQuantityEditViewBehavior.h"
#import "SDQuantityView.h"
#import "UIView+PaintCode.h"
#import "SDSearchBar.h"
#import "SDSearchDisplayController.h"
#import "SDSearchSuggestionsDataSource.h"
#import "SDSearchSuggestionsViewController.h"
#import "SDSearchUsageDelegate.h"
#import "SDSpanParser.h"
#import "SDStackView.h"
#import "SDSwitch.h"
#import "SDTableViewCommand.h"
#import "SDTableViewSectionController.h"
#import "SDTextField.h"
#import "SDTextFieldPicker.h"
#import "SDTouchCaptureView.h"
#import "SDWebViewCell.h"
#import "UIActivityIndicatorView+SDExtensions.h"
#import "UIAlertView+SDExtensions.h"
#import "UIApplication+SDExtensions.h"
#import "UIButton+SDExtensions.h"
#import "UIColor+SDExtensions.h"
#import "UIImage+SDExtensions.h"
#import "UINavigationController+SDExtensions.h"
#import "UIScreen+SDExtensions.h"
#import "UITableView+SDAutoUpdate.h"
#import "UITableViewCell+SDExtensions.h"
#import "UIView+SDExtensions.h"
#import "UIViewController+SDExtensions.h"
#import "NSCachedURLResponse+LeakFix.h"
#import "NSURL+SDExtensions.h"
#import "NSURLCache+SDExtensions.h"
#import "NSURLRequest+SDExtensions.h"
#import "Reachability.h"
#import "SDImageCache.h"
#import "SDURLConnection.h"
#import "SDWebService+SDProcessingBlocks.h"
#import "SDWebService.h"
#import "SDWebServiceMockResponseMapProvider.h"
#import "SDWebServiceMockResponseProvider.h"
#import "SDWebServiceMockResponseQueueProvider.h"
#import "SDWebServiceMockResponseRequestMapping.h"
#import "UIImageView+SDExtensions.h"